### ISSUE TITLE
PR #1 isn't doing the right rewrite with spir-v / spir-v/ URLs

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Registry-Root#2]
Going to either https://www.khronos.org/registry/spir-v or https://www.khronos.org/registry/spir-v/ redirects to the nonexistent path https://www.khronos.org/registry/SPIR/-v . Can you commit a fix for this? No need for my signoff as obviously my visual ability to tell if the rewrite rules are all working properly, is inadequate, or I would have noticed something weird about it.

**Comment by allcreatures** [comment]
Push to main. Move spir-v rule to before spir to ensure it is caught first.

**Comment by oddhack** [comment]
Thanks!
